# Basic
title: hubert
subtitle: 个人站
description: 欢迎来到我的个人站~
# 头像里面的标题
avatarTitle: hubertzou
# 头像里面的描述
avatarDesc: NLP / ML / CV 
url: "http://mmelodious.github.io"

# Comment
comment:
    disqus: hubertzou
    uyan: 2159185  # 有言id,登录有言官网申请

# Social
social:
    weibo: 2313731666
    github: mmelodious
    # twitter: 
    mail: hongbinzou@gmail.com

# 百度统计 
baidu:
    id: 45ffe881d6dfe8099916360b4bb7239c  

# Google Analytics
# 使用博客模板请去掉或者更换 id
#ga:
#    id: 
#    host:


#
#
#
#


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


